Pass namespace annotations to driver when --extra-create-metadata is enabled #714
kubernetes-csi/external-provisioner pull request #800
Opened 2022-11-01 06:47 UTC by vinli-cn

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Pass namespace annotations to driver when --extra-create-metadata is enabled #714
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-11-01 06:52 UTC, vinli-cn commented
/ok-to-test

2022-11-01 06:54 UTC, vinli-cn commented
/assign @kubernetes-csi-reviewers

2022-11-01 17:33 UTC, ggriffiths requested changes
@vinli-cn Your PR title says "pass namespace annotations", but your code is passing PVC annotations to the driver. 

Passing PVC annotations to a CSI Driver request has been discussed at length in this thread:
https://github.com/kubernetes-csi/external-provisioner/issues/86

I would read up on the thread and see if you have anything else to add as to why PVC annotations should be added to the CSI create volume request.

2022-11-04 08:32 UTC, humblec commented on pkg/controller/controller.go
> +		pvcAnnotationMap := claim.GetAnnotations()
this is geting annotations from PVC and not namespace as mentioned in the PR.

2022-11-08 08:45 UTC, vinli-cn commented
> @vinli-cn Your PR title says "pass namespace annotations", but your code is passing PVC annotations to the driver.
> 
> Passing PVC annotations to a CSI Driver request has been discussed at length in this thread: #86
> 
> I would read up on the thread and see if you have anything else to add as to why PVC annotations should be added to the CSI create volume request.

thanks for reviewing the PR.

I updated the title and description of this PR according to issue #86, user might need to make use of the extra PVC's annotations.

Could you please review again and share your insights? 


Thanks!

2022-11-08 23:35 UTC, ggriffiths commented
Hi @vinli-cn, thank you for updating the PR description!

I think your PR title is still incorrect:
> Pass namespace annotations to driver when --extra-create-metadata is enabled

Can you edit this to the below so we're clear what's being proposed?
> Pass PVC annotations

Anyway, @vinli-cn, you should read up on the thread in issue #86. Many people have proposed this change in the past, but the maintainers decided to not add it.

If you think you have a compelling use case as to why this should be supported, send a message in #86.  Discussion in this current pull request will not result in it being merged.

2022-11-14 20:56 UTC, ggriffiths requested changes
Feel free to re-request review if this proposal is accepted in the issue I linked.

2023-04-13 22:37 UTC, closed without merging